name: chat_api
description: A starting point for Dart libraries or applications.
version: 2.0.0
homepage: https://www.example.com
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  rest_api_server:
    git:
      url: https://gitlab.com/dartrest/rest_api_server.git
      ref: 2.2.3
  chat_models:
    path: ../chat_models
  chat_patch:
    path: ../chat_patch
  build: ^1.2.1
  code_builder: ^3.2.0
  dart_style: ^1.3.3
  get_it: ^3.1.0
  jaguar_jwt: ^2.1.5
  nanoid: ^0.0.4
  path: ^1.6.2
  shelf: ^0.7.3
  source_gen: ^0.9.4+6
  shelf_web_socket: ^0.2.3
  web_socket_channel: ^1.1.0
dev_dependencies:
  test: ^1.15.2
  build_runner: ^1.10.0